# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI

on:
  push:
    branches: [ "feature/pp6-99-auto-publish-nuget" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore Paytrail-dotnet-sdk.sln

      
    - name: Build
      run: dotnet build Paytrail-dotnet-sdk.sln --no-restore 
      
    - name: Test
      run: dotnet test Paytrail-dotnet-sdk.sln --no-build --verbosity normal
